language: node_js

node_js:
  - "stable"

addons:
  chrome: stable

before_script:
  - npm install -g @angular/cli

cache:
  npm: true
  directories: 
    - node_modules

script:
  - cd frontend
  - ng lint
  - ng test --watch=false --browsers=ChromeHeadless
  - ng build --prod

deploy:
  provider: s3
  access_key_id: $Access_key_id
  secret_access_key: $Secret_Access_key
  bucket: sepm-workflow
  local_dir: dist/workflow
  skip_cleanup: true
  region: ap-southeast-1
  on:
    branch: master