import { NgModule } from '@angular/core';
import {DragDropModule} from '@angular/cdk/drag-drop';
import { MatProgressSpinnerModule,
   MatDialogModule,
   MatButtonModule,
   MatToolbarModule,
   MatTabsModule,
   MatCardModule,
   MatSelectModule,
   MatFormFieldModule,
   MatInputModule,
   MatSlideToggleModule,
   MatDatepickerModule,
   MatNativeDateModule,
   MatSidenavModule,
   MatDividerModule,
   MatRippleModule,
   MatExpansionModule,
   MatIconModule,
   MatMenuModule,
   MatSortModule,
   MatTableModule,
   MatPaginatorModule,
   MatCheckboxModule,
   MatAutocompleteModule,
   MatChipsModule,
   MatStepperModule} from '@angular/material';

@NgModule({
  exports: [
    DragDropModule,
    MatAutocompleteModule,
    MatButtonModule,
    MatCardModule,
    MatCheckboxModule,
    MatChipsModule,
    MatDatepickerModule,
    MatDialogModule,
    MatDividerModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatIconModule,
    MatInputModule,
    MatMenuModule,
    MatNativeDateModule,
    MatPaginatorModule,
    MatProgressSpinnerModule,
    MatRippleModule,
    MatSelectModule,
    MatSlideToggleModule,
    MatSortModule,
    MatStepperModule,
    MatTableModule,
    MatTabsModule,
    MatToolbarModule
  ]
})
export class MaterialModule { }
